from typing import List

from pydantic import BaseModel, Field


class Source(BaseModel):
    """Schema for a source document."""

    Url: str = Field(..., description="The URL of the source document.")


class AgentResponse(BaseModel):
    """Schema for the agent's response."""

    answer: str = Field(..., description="The answer generated by the agent.")
    sources: List[Source] = Field(
        default_factory=list,
        description="List of source documents used to generate the answer.",
    )
